export const copy = {
  ar: {
    seo: {
      description: 'أنشئ منيو إلكترونيًا يحمل هوية مطعمك، وسهّل على ضيوفك تصفّح الأطباق وإرسال الطلبات. اشتراك شهري ثابت بلا عمولة على الطلبات.',
    },
    nav: {
      how: 'كيف يعمل',
      features: 'المزايا',
      pricing: 'الأسعار',
      faq: 'الأسئلة الشائعة',
      audience: 'للمطاعم المستقلة',
    },
    hero: {
      badge: 'منيو يليق بمطعمك',
      titleA: 'منيو يلفت الانتباه.',
      titleB: 'وطلب أسهل لضيوفك.',
      description: 'اعرض منيو مطعمك بشكل احترافي، وخلي زبائنك يتصفحوا الأطباق ويطلبوا بسهولة من أي جهاز',
      request: 'أنشئ صفحة مطعمك',
      stripTitle: 'كل ما يحتاجه مطعمك للطلب أونلاين',
      stripSub: 'اشتراك شهري ثابت · بلا عمولة · $19.99',
      cart: 'سلة الطلب',
      try: 'جرّب المنيو التفاعلي',
      proof: 'مصمم للمطاعم التي تدرك أن',
      proofStrong: 'كل دقيقة مهمة.',
    },
    menu: {
      open: 'مفتوح الآن',
      popular: 'الأكثر طلبًا',
      meals: 'وجبات',
      drinks: 'مشروبات',
      picks: 'اختياراتنا',
      fresh: 'طازج اليوم',
      cart: 'سلة الطلب',
      qrTry: 'امسح وجرّب بنفسك',
      newOrder: 'طلب جديد',
      now: 'الآن',
      total: 'المجموع',
    },
    ticker: [
      'بلا عمولة على الطلبات',
      'لا حاجة لتطبيق للضيف',
      'منيو يحمل هوية مطعمك',
      'اشتراك شهري واضح',
    ],
    story: {
      eyebrow: 'من مطبخك إلى شاشة ضيفك',
      titleA: 'قدّم أطباقك',
      titleB: 'كما تستحق أن تُرى.',
      body: 'صور واضحة وتفاصيل مرتبة تساعد ضيوفك على الاختيار. ثم تجمع سلة الطلب اختياراتهم في ملخص أسهل لفريقك في المتابعة.',
      tag: 'أطباقك. بصورة أجمل.',
      owner: 'لمطعم مستقل',
      ownerNote: 'تفاصيل مطعمك تصنع التجربة.',
    },
    how: {
      eyebrow: 'طريقة طلب أبسط',
      titleA: 'يمسح. يختار.',
      titleB: 'ويرسل طلبه.',
      body: 'ثلاث خطوات تنقل ضيفك من رمز QR إلى طلب واضح — من دون رسائل متفرقة أو منيو قديم.',
    },
    features: {
      eyebrow: 'أكثر من مجرد منيو',
      titleA: 'كل ما يحتاجه',
      titleB: 'طلبك اليومي.',
      aside: 'سهّل الاختيار على ضيوفك، واجعل متابعة الطلبات أوضح لفريقك.',
    },
    family: {
      eyebrow: 'عائلة واحدة، موائد كثيرة',
      titleA: 'اكتشف مطاعم',
      titleB: 'عائلتنا.',
      body: 'كل مطعم في عائلتنا له صفحته وهويته. اختر مطعمك المفضل، تصفح منيوه، واطلب مباشرة.',
      cta: 'تصفح كل المطاعم',
      open: 'مفتوح',
      closed: 'مغلق',
      items: 'صنف',
      empty: 'مطاعمنا تنضم قريبًا — عد لاحقًا.',
    },
    dashboard: {
      eyebrow: 'صورة أوضح ليومك',
      titleA: 'كل طلب واضح.',
      titleB: 'وكل متابعة أسهل.',
      body: 'تابع الطلبات في لوحة واحدة بدل البحث بين الرسائل وصور المنيو القديمة. راجع اسم الصنف والكمية والملاحظات بسرعة.',
      chips: ['ملخص جاهز للإرسال', 'تحديثات مباشرة', 'إحصائيات سهلة القراءة'],
      label: 'لوحة الطلبات',
      date: 'اليوم، الثلاثاء ٢١ مايو',
      today: 'طلبات اليوم',
      yesterday: '+ 8 عن أمس',
      top: 'الأكثر طلبًا',
      topItem: 'برجر سموكي',
      topCount: '١٨ طلبًا',
      new: 'جديد',
      done: 'مكتمل',
    },
    pricing: {
      eyebrow: 'بلا تعقيد',
      titleA: 'خطة واحدة.',
      titleB: 'وسعر واضح.',
      body: 'ابدأ بمنيو يحمل هوية مطعمك وطلبات أسهل في المتابعة — باشتراك شهري ثابت ومن دون عمولة على كل طلب.',
      label: 'Restivo للمطاعم',
      month: '/ شهريًا',
      trial: 'جرّب 7 أيام مجانًا قبل الدفع',
      features: [
        'صفحة منيو بهوية مطعمك',
        'منيو QR جاهز للطباعة',
        'سلة طلب سهلة للضيف',
        'ملخص طلب جاهز للإرسال عبر WhatsApp',
        'لوحة واضحة لمتابعة الطلبات',
        'بلا عمولة على الطلبات',
      ],
      request: 'ابدأ صفحة مطعمك',
    },
    faq: {
      eyebrow: 'إجابات قبل أن تبدأ',
      title: 'كل ما تريد معرفته.',
    },
    final: {
      titleA: 'منيو يليق بمطعمك.',
      titleB: 'وطلب أسهل لضيوفك.',
      body: 'قدّم قائمتك بوضوح، واجعل إرسال الطلب أسهل من أول نظرة.',
      request: 'أنشئ صفحة مطعمك',
    },
    footer: {
      a: 'منيو إلكتروني وطلبات أوضح',
      b: 'مصممة للمطاعم المستقلة.',
    },
    modal: {
      badge: 'خطوتك الأولى',
      titleA: 'ابدأ بصفحة',
      titleB: 'تشبه مطعمك.',
      description: 'أخبرنا قليلًا عن مطعمك، وسنتواصل معك لمساعدتك على تجهيز صفحتك.',
      close: 'إغلاق',
      name: 'اسمك',
      namePh: 'مثال: محمد',
      restaurant: 'اسم المطعم',
      restaurantPh: 'مثال: مطعم الواحة',
      phone: 'رقم التواصل',
      submit: 'اطلب صفحة مطعمك',
      note: 'من دون التزام — يسعدنا أن نسمع عن مطعمك.',
      success: 'وصل طلبك.',
      thanks: 'شكرًا',
      tail: 'سنتواصل معك قريبًا للحديث عن صفحة مطعمك.',
      done: 'حسنًا',
    },
  },
  en: {
    seo: {
      description: 'Create a branded online menu, help guests browse and order with ease, and keep every order clear. One simple monthly plan with no per-order commission.',
    },
    nav: {
      how: 'How it works',
      features: 'Benefits',
      pricing: 'Pricing',
      faq: 'FAQ',
      audience: 'For independent restaurants',
    },
    hero: {
      badge: 'A menu that feels like yours',
      titleA: 'A menu that stands out.',
      titleB: 'An easier way to order.',
      description: 'Show your restaurant menu professionally, and let your guests browse dishes and order easily from any device',
      request: 'Create your restaurant page',
      stripTitle: 'Everything your restaurant needs to take online orders',
      stripSub: 'One monthly plan · No commission · $19.99',
      cart: 'Order cart',
      try: 'Explore the interactive menu',
      proof: 'Made for restaurants where',
      proofStrong: 'every minute matters.',
    },
    menu: {
      open: 'Open now',
      popular: 'Most ordered',
      meals: 'Meals',
      drinks: 'Drinks',
      picks: 'Guest favorites',
      fresh: 'Fresh today',
      cart: 'Your order',
      qrTry: 'Scan and try it yourself',
      newOrder: 'New order',
      now: 'Now',
      total: 'Total',
    },
    ticker: [
      'No commission per order',
      'No app required for guests',
      'A menu in your restaurant’s style',
      'One clear monthly plan',
    ],
    story: {
      eyebrow: 'From your kitchen to your guest’s screen',
      titleA: 'Show your dishes',
      titleB: 'at their very best.',
      body: 'Clear photos and helpful details make it easier for guests to choose. The order cart then brings their selections together in a summary your team can follow.',
      tag: 'Your food. A better first look.',
      owner: 'For independent restaurants',
      ownerNote: 'Your details make it yours.',
    },
    how: {
      eyebrow: 'A simpler way to order',
      titleA: 'Scan. Choose.',
      titleB: 'Send the order.',
      body: 'Three simple steps take guests from a QR scan to a clear order — without scattered messages or outdated menu photos.',
    },
    features: {
      eyebrow: 'More than a menu',
      titleA: 'Everything your team needs',
      titleB: 'for everyday orders.',
      aside: 'Make choosing easier for guests and order follow-up clearer for your team.',
    },
    family: {
      eyebrow: 'One family, many tables',
      titleA: 'Explore restaurants',
      titleB: 'in our family.',
      body: 'Every restaurant in our family has its own page and identity. Pick your favorite, browse the menu, and order directly.',
      cta: 'Browse all restaurants',
      open: 'Open',
      closed: 'Closed',
      items: 'items',
      empty: 'Our restaurants are joining soon — check back later.',
    },
    dashboard: {
      eyebrow: 'A clearer view of your day',
      titleA: 'Every order, clear.',
      titleB: 'Every follow-up, simpler.',
      body: 'Keep orders in one place instead of searching through chats and old menu photos. Check each item, quantity, and note at a glance.',
      chips: ['Ready-to-send summaries', 'Live updates', 'Easy-to-read stats'],
      label: 'Order dashboard',
      date: 'Today, Tuesday May 21',
      today: "Today's orders",
      yesterday: '+ 8 from yesterday',
      top: 'Most ordered',
      topItem: 'Smoky burger',
      topCount: '18 orders',
      new: 'New',
      done: 'Complete',
    },
    pricing: {
      eyebrow: 'Simple by design',
      titleA: 'One plan.',
      titleB: 'One clear price.',
      body: 'Get a branded menu and a clearer way to follow orders with one fixed monthly subscription and no commission per order.',
      label: 'Restivo for restaurants',
      month: '/ month',
      trial: 'Try 7 days free before you pay',
      features: [
        'A menu page in your restaurant’s style',
        'Printable QR menu',
        'An easy-to-use guest cart',
        'WhatsApp-ready order summary',
        'A clear order dashboard',
        'No commission per order',
      ],
      request: 'Get your restaurant page',
    },
    faq: {
      eyebrow: 'Before you get started',
      title: 'Good questions. Clear answers.',
    },
    final: {
      titleA: 'A menu that fits your restaurant.',
      titleB: 'Ordering made easier.',
      body: 'Present your menu clearly and give guests an easier way to send their order.',
      request: 'Create your restaurant page',
    },
    footer: {
      a: 'Digital menus and clearer orders',
      b: 'Made for independent restaurants.',
    },
    modal: {
      badge: 'Your first step',
      titleA: 'Start with a page',
      titleB: 'that feels like yours.',
      description: 'Tell us a little about your restaurant and we’ll help you get your page ready.',
      close: 'Close',
      name: 'Your name',
      namePh: 'Example: Alex',
      restaurant: 'Restaurant name',
      restaurantPh: 'Example: Oasis Restaurant',
      phone: 'Contact number',
      submit: 'Request your restaurant page',
      note: 'No commitment — we’d love to hear about your restaurant.',
      success: 'Your request is in.',
      thanks: 'Thanks',
      tail: 'We’ll be in touch soon to talk about your restaurant page.',
      done: 'Done',
    },
  },
};

export const features = [
  {
    n: '01',
    icon: '▣',
    tone: 'coral',
    ar: {
      title: 'صفحة تحمل هوية مطعمك',
      body: 'استخدم صورك وألوانك، وشارك منيوك عبر رابط واحد سهل الحفظ.',
    },
    en: {
      title: 'A page that feels like your restaurant',
      body: 'Use your photos and colors, then share your menu with one easy-to-save link.',
    },
  },
  {
    n: '02',
    icon: '⌗',
    tone: 'sun',
    ar: {
      title: 'منيو QR على كل طاولة',
      body: 'وجّه ضيوفك إلى قائمتك مباشرة — من دون تطبيق أو تسجيل.',
    },
    en: {
      title: 'A QR menu for every table',
      body: 'Take guests straight to your menu, with no app or sign-up required.',
    },
  },
  {
    n: '03',
    icon: '▤',
    tone: 'teal',
    ar: {
      title: 'طلبات مرتبة من البداية',
      body: 'يختار الضيف أصنافه ويراجعها ويرسلها في ملخص واضح لفريقك.',
    },
    en: {
      title: 'Clear orders from the start',
      body: 'Guests choose, review, and send their items in a clear summary for your team.',
    },
  },
  {
    n: '04',
    icon: '▥',
    tone: 'ink',
    ar: {
      title: 'لوحة طلبات سهلة المتابعة',
      body: 'راجع الطلبات والأصناف الأكثر طلبًا من مكان واحد.',
    },
    en: {
      title: 'An order dashboard at a glance',
      body: 'Review incoming orders and best-sellers in one place.',
    },
  },
];

export const steps = {
  ar: [
    ['⌗', 'يمسح', 'رمز QR على الطاولة'],
    ['⌘', 'يختار', 'أطباقه من منيو واضح'],
    ['◌', 'يرسل', 'طلبًا مرتبًا لفريقك'],
  ],
  en: [
    ['⌗', 'Scan', 'The QR code on the table'],
    ['⌘', 'Choose', 'From a clear, easy menu'],
    ['◌', 'Send', 'A clear order to your team'],
  ],
};

export const faqs = {
  ar: [
    ['هل يحتاج ضيفي إلى تطبيق؟', 'لا. يفتح المنيو من متصفح الهاتف مباشرة، من دون تنزيل تطبيق أو إنشاء حساب.'],
    ['هل توجد عمولة على الطلبات؟', 'لا. الاشتراك الشهري ثابت بقيمة $19.99، ولا تُفرض عمولة على طلبات مطعمك.'],
    ['أين تصل الطلبات؟', 'تظهر الطلبات في لوحة مطعمك، ويمكن إرسال ملخصها إلى WhatsApp بالطريقة التي تناسب فريقك.'],
    ['هل يمكنني استخدام هوية مطعمي؟', 'نعم. يمكنك عرض اسم مطعمك وألوانه وصوره في تجربة منيو مصممة لتشبهه.'],
  ],
  en: [
    ['Do guests need to download an app?', 'No. The menu opens in a guest’s mobile browser, with no download or account required.'],
    ['Is there a commission on orders?', 'No. The subscription is a flat $19.99 per month, with no commission on your restaurant’s orders.'],
    ['Where do orders go?', 'Orders appear in your restaurant dashboard, and you can send a summary through WhatsApp in the format your team prefers.'],
    ['Can I use my restaurant’s branding?', 'Yes. Add your restaurant name, colors, and photos to a menu experience that feels like yours.'],
  ],
};