'use strict';
const express = require('express');
const ctrl = require('../controllers/leads.controller');
const { requireAuth, requireOwner } = require('../middleware/auth');
const router = express.Router();
router.use(requireAuth, requireOwner);
router.get('/stats', ctrl.stats);
router.get('/search-runs', ctrl.searchRuns);
router.post('/bulk', ctrl.bulkImport);
router.post('/merge', ctrl.merge);
router.get('/', ctrl.list);
router.post('/', ctrl.create);
router.post('/discover', ctrl.discover);
router.get('/:id', ctrl.getOne);
router.post('/:id/research', ctrl.research);
router.post('/:id/refresh', ctrl.refresh);
router.post('/:id/generate-demo', ctrl.generateDemo);
router.post('/:id/prepare-everything', ctrl.prepareEverything);
router.patch('/:id/status', ctrl.updateStatus);
router.post('/:id/response', ctrl.setResponse);
router.post('/:id/contact', ctrl.contact);
router.get('/:id/offer', ctrl.offerPreview);
module.exports = router;
