import {
  BarChart3,
  MessageCircle,
  MousePointer2,
  QrCode,
  ScanLine,
  ShoppingBag,
  Store,
} from 'lucide-react';

export const copy = {
  ar: {
    language: 'العربية',
    languageShort: 'ع',
    nav: { how: 'كيف يعمل', features: 'المزايا', pricing: 'الاشتراك', faq: 'أسئلة شائعة', request: 'اطلب صفحتك', audience: 'للمطاعم المستقلة', openMenu: 'فتح القائمة', close: 'إغلاق' },
    hero: {
      badge: 'منيوك جاهز للزحمة',
      titleA: 'من المسح إلى الطلب',
      titleB: 'في أقل من 30 ثانية',
      description: 'منيو إلكتروني وطلب أونلاين للمطاعم المستقلة. صفحة تشبهك، طلبات مرتبة، ووقت أكثر لما يهم فعلًا: الأكل والضيف.',
      request: 'اطلب صفحة مطعمك',
      how: 'شوف كيف تشتغل',
      proof: 'مصمم للمطعم الذي يعرف',
      proofStrong: 'كل دقيقة في يومه تفرق.',
      scroll: 'انزل لتكتشف',
      stripTitle: 'جاهز لمطعمك المستقل',
      stripSub: 'اشتراك واحد · بدون عمولة · $8.99 / شهر',
      cart: 'سلة طلب',
    },
    menu: {
      restaurant: 'مطعم واحة',
      name: 'بَسْطة',
      open: 'مفتوح الآن',
      popular: 'الأكثر طلبًا',
      meals: 'وجبات',
      drinks: 'مشروبات',
      picks: 'اختيارات بَسْطة',
      fresh: 'طازج اليوم',
      cart: 'سلة الطلب',
      items: '3 أصناف',
      newOrder: 'طلب جديد',
      now: 'الآن',
      total: 'المجموع',
      start: 'تجربة مطعمك تبدأ هنا',
    },
    ticker: ['لا عمولة على الطلب', 'بدون تطبيق للعميل', 'صفحة بهوية مطعمك', 'اشتراك واحد واضح'],
    story: {
      eyebrow: 'من مطبخك إلى شاشة العميل',
      titleA: 'خلّ الناس تشوف',
      titleB: 'اللي تقدمه فعلًا.',
      body: 'الصورة الجيدة تفتح الشهية، والطلب المرتب يخلّي فريقك أسرع. Restivo يجمع الاثنين في تجربة واحدة تشبه مطعمك.',
      tag: 'صورة حقيقية. تجربة أوضح.',
      owner: 'صاحب مطعم مستقل',
      ownerNote: 'كل شيء يبدأ من مطبخك.',
    },
    how: {
      eyebrow: 'الرحلة القصيرة',
      titleA: 'ثلاث خطوات.',
      titleB: 'ولا رسالة ضائعة.',
      body: 'كل شيء في Restivo مبني حول لحظة الطلب — من أول ما يلمح الضيف الـ QR إلى أن يصلك الطلب بصورته المفهومة.',
    },
    features: {
      eyebrow: 'مو بس منيو',
      titleA: 'الأدوات التي يحتاجها',
      titleB: 'مطعمك فعلًا.',
      aside: 'خفف الزحمة عن فريقك، وخلي تجربة ضيفك على مزاجك.',
    },
    dashboard: {
      eyebrow: 'الوضوح يبيع',
      titleA: 'كل طلب مرتب.',
      titleB: 'وكل قرار أوضح.',
      body: 'بدل ما تدور بين محادثات WhatsApp وصور المنيو القديمة، شوف طلباتك في مكان واحد — باسم الصنف، الكمية، والملاحظات.',
      chips: ['ملخص جاهز للإرسال', 'تحديثات مباشرة', 'إحصائيات بسيطة'],
      panelLabel: 'لوحة المطعم',
      date: 'اليوم، الثلاثاء ٢١ مايو',
      todayOrders: 'طلبات اليوم',
      yesterday: '+ 8 من أمس',
      top: 'الأكثر طلبًا',
      topItem: 'برجر سموكي',
      topCount: '١٨ طلب',
      new: 'جديد',
      done: 'مكتمل',
      response: 'وقت الاستجابة',
      calmer: 'أسرع وأهدأ',
    },
    pricing: {
      eyebrow: 'ببساطة',
      titleA: 'خطة واحدة.',
      titleB: 'سعر واضح.',
      body: 'كل ما تحتاجه لتبدأ استقبال الطلبات بشكل أرتب — بدون عقود طويلة أو مفاجآت في الفاتورة.',
      ready: 'جاهز لمطعمك المستقل',
      start: 'ابدأ اليوم',
      label: 'Restivo للمطاعم',
      month: '/ شهريًا',
      features: ['صفحة مطعم بهويتك', 'QR menu قابل للطباعة', 'سلة طلب أونلاين', 'ملخص جاهز لـ WhatsApp', 'Dashboard للطلبات', 'بدون عمولة'],
      request: 'اطلب صفحتك الآن',
      fine: 'لا عمولة. لا التزام. فقط $8.99 شهريًا.',
    },
    faq: {
      eyebrow: 'قبل أن تبدأ',
      title: 'الأسئلة التي في بالك.',
    },
    final: {
      titleA: 'مطعمك يستحق',
      titleB: 'منيو يشتغل.',
      body: 'خلّ أول انطباع عن مطعمك يبدأ من المكان الصح.',
      request: 'اطلب صفحة مطعمك',
    },
    footer: {
      descriptionA: 'منيو إلكتروني وطلب أونلاين',
      descriptionB: 'للمطاعم التي تصنع فرقًا.',
      request: 'اطلب صفحتك',
    },
    modal: {
      badge: 'نبدأ من مطعمك',
      titleA: 'خلّ منيو مطعمك',
      titleB: 'يشتغل معك.',
      description: 'اترك بياناتك وسنرتب لك صفحة مطعمك على Restivo.',
      close: 'إغلاق',
      name: 'اسمك',
      namePlaceholder: 'مثال: محمد',
      restaurant: 'اسم المطعم',
      restaurantPlaceholder: 'مثال: مطعم واحة',
      phone: 'رقم التواصل',
      submit: 'أرسل طلبك',
      note: 'بدون التزام. فقط نريد أن نسمع عن مطعمك.',
      successTitle: 'وصلنا طلبك.',
      successBody: 'شكرًا',
      successTail: 'سنتواصل معك قريبًا لنجهز حضور مطعمك.',
      done: 'تمام',
    },
  },
  en: {
    language: 'English',
    languageShort: 'EN',
    nav: { how: 'How it works', features: 'Features', pricing: 'Pricing', faq: 'FAQ', request: 'Get your page', audience: 'For independent restaurants', openMenu: 'Open menu', close: 'Close' },
    hero: {
      badge: 'Your menu, ready for the rush',
      titleA: 'From the scan to the order',
      titleB: 'in under 30 seconds',
      description: 'Digital menus and online ordering for independent restaurants. A page that feels like you, organized orders, and more time for what matters: the food and the guest.',
      request: 'Get your restaurant page',
      how: 'See how it works',
      proof: 'Built for restaurants where',
      proofStrong: 'every minute matters.',
      scroll: 'Scroll to explore',
      stripTitle: 'Ready for your restaurant',
      stripSub: 'One plan · No commission · $8.99 / month',
      cart: 'Order cart',
    },
    menu: {
      restaurant: 'Oasis Restaurant',
      name: 'Basta',
      open: 'Open now',
      popular: 'Most ordered',
      meals: 'Meals',
      drinks: 'Drinks',
      picks: 'Basta picks',
      fresh: 'Fresh today',
      cart: 'Order cart',
      items: '3 items',
      newOrder: 'New order',
      now: 'Now',
      total: 'Total',
      start: 'Your restaurant starts here',
    },
    ticker: ['No commission on orders', 'No app for guests', 'A page in your identity', 'One clear subscription'],
    story: {
      eyebrow: 'From your kitchen to their screen',
      titleA: 'Let people see',
      titleB: 'what you actually serve.',
      body: 'A good photo opens the appetite, and an organized order keeps your team moving. Restivo brings both into one experience that feels like your restaurant.',
      tag: 'Real food. Clearer ordering.',
      owner: 'Independent restaurant owner',
      ownerNote: 'Everything starts in your kitchen.',
    },
    how: {
      eyebrow: 'The short journey',
      titleA: 'Three steps.',
      titleB: 'No order lost.',
      body: 'Everything in Restivo is built around the ordering moment — from the first QR scan to the clear order that reaches your team.',
    },
    features: {
      eyebrow: 'More than a menu',
      titleA: 'The tools your',
      titleB: 'restaurant actually needs.',
      aside: 'Take the rush off your team and keep the guest experience in your hands.',
    },
    dashboard: {
      eyebrow: 'Clarity sells',
      titleA: 'Every order organized.',
      titleB: 'Every decision clearer.',
      body: 'Stop digging through WhatsApp chats and old menu photos. See every order in one place — with the item, quantity, and notes.',
      chips: ['Ready-to-send summary', 'Live updates', 'Simple stats'],
      panelLabel: 'Restaurant dashboard',
      date: 'Today, Tuesday May 21',
      todayOrders: 'Today’s orders',
      yesterday: '+ 8 from yesterday',
      top: 'Most ordered',
      topItem: 'Smoky burger',
      topCount: '18 orders',
      new: 'New',
      done: 'Complete',
      response: 'Response time',
      calmer: 'Faster and calmer',
    },
    pricing: {
      eyebrow: 'Simple',
      titleA: 'One plan.',
      titleB: 'Clear price.',
      body: 'Everything you need to start taking orders cleanly — no long contracts or surprises on the bill.',
      ready: 'Ready for your independent restaurant',
      start: 'Start today',
      label: 'Restivo for restaurants',
      month: '/ month',
      features: ['Restaurant page in your identity', 'Printable QR menu', 'Online order cart', 'WhatsApp-ready summary', 'Order dashboard', 'No commission'],
      request: 'Get your page now',
      fine: 'No commission. No commitment. Just $8.99 per month.',
    },
    faq: {
      eyebrow: 'Before you start',
      title: 'Questions on your mind.',
    },
    final: {
      titleA: 'Your restaurant deserves',
      titleB: 'a menu that works.',
      body: 'Make your restaurant’s first impression start in the right place.',
      request: 'Get your restaurant page',
    },
    footer: {
      descriptionA: 'Digital menus and online ordering',
      descriptionB: 'for restaurants that make a difference.',
      request: 'Get your page',
    },
    modal: {
      badge: 'Start with your restaurant',
      titleA: 'Let your restaurant menu',
      titleB: 'work for you.',
      description: 'Leave your details and we’ll set up your Restivo restaurant page.',
      close: 'Close',
      name: 'Your name',
      namePlaceholder: 'Example: Alex',
      restaurant: 'Restaurant name',
      restaurantPlaceholder: 'Example: Oasis Restaurant',
      phone: 'Contact number',
      submit: 'Send request',
      note: 'No commitment. We just want to hear about your restaurant.',
      successTitle: 'Request received.',
      successBody: 'Thanks',
      successTail: 'We’ll be in touch soon to set up your restaurant presence.',
      done: 'Done',
    },
  },
} as const;

export type Language = keyof typeof copy;

export const featureContent = [
  {
    number: '01',
    icon: Store,
    tone: 'coral',
    ar: { title: 'صفحة تحمل اسم مطعمك', description: 'منيو مرتب بصورك وألوانك ورابط واحد سهل الحفظ والمشاركة.' },
    en: { title: 'A page with your restaurant name', description: 'A menu with your photos, colors, and one link that is easy to save and share.' },
  },
  {
    number: '02',
    icon: QrCode,
    tone: 'sun',
    ar: { title: 'QR على الطاولة وفي كل مكان', description: 'رمز واضح يصل بضيفك إلى المنيو مباشرة، بلا تطبيق وبلا تسجيل.' },
    en: { title: 'QR on the table and everywhere', description: 'A clear code that takes guests straight to your menu, with no app and no sign-up.' },
  },
  {
    number: '03',
    icon: ShoppingBag,
    tone: 'teal',
    ar: { title: 'سلة طلب بلا رسائل ضائعة', description: 'الضيف يختار، يراجع، ويرسل الطلب مرتبًا إلى المكان الذي تتابعه.' },
    en: { title: 'An order cart with no lost messages', description: 'Guests choose, review, and send an organized order to the place your team already follows.' },
  },
  {
    number: '04',
    icon: BarChart3,
    tone: 'ink',
    ar: { title: 'Dashboard يفهم يومك', description: 'تابع الطلبات والأصناف الأكثر طلبًا من لوحة واحدة خفيفة.' },
    en: { title: 'A dashboard that understands your day', description: 'Track orders and best-sellers from one lightweight dashboard.' },
  },
] as const;

export const stepContent = {
  ar: [
    { icon: ScanLine, title: 'يمسح', copy: 'QR على الطاولة' },
    { icon: MousePointer2, title: 'يختار', copy: 'منيو واضح وسريع' },
    { icon: MessageCircle, title: 'يرسل', copy: 'ملخص الطلب جاهز' },
  ],
  en: [
    { icon: ScanLine, title: 'Scan', copy: 'The QR on the table' },
    { icon: MousePointer2, title: 'Choose', copy: 'A clear, quick menu' },
    { icon: MessageCircle, title: 'Send', copy: 'A ready order summary' },
  ],
} as const;

export const faqContent = {
  ar: [
    { question: 'هل أحتاج إلى تطبيق خاص؟', answer: 'لا. Restivo يعمل من المتصفح مباشرة على جوال العميل، من دون تحميل تطبيق أو إنشاء حساب.' },
    { question: 'هل يأخذ Restivo عمولة على الطلبات؟', answer: 'لا. الاشتراك ثابت بقيمة $8.99 شهريًا، ولا توجد عمولة على طلبات مطعمك.' },
    { question: 'أين تصل الطلبات؟', answer: 'يظهر الطلب مرتبًا في Dashboard الخاص بمطعمك، ويمكنك أيضًا إرساله إلى WhatsApp بالطريقة التي اعتاد عليها فريقك.' },
    { question: 'هل يمكنني استخدام ألوان وهوية مطعمي؟', answer: 'نعم. الصفحة مصممة لتشبه مطعمك، من الاسم والألوان إلى صور الأصناف وطريقة عرضها.' },
  ],
  en: [
    { question: 'Do I need a special app?', answer: 'No. Restivo works directly in the guest’s mobile browser, with no download and no account required.' },
    { question: 'Does Restivo take a commission on orders?', answer: 'No. The subscription is a flat $8.99 per month, with no commission on your restaurant orders.' },
    { question: 'Where do the orders arrive?', answer: 'Orders appear in your restaurant dashboard, and you can also send them to WhatsApp in the format your team already knows.' },
    { question: 'Can I use my restaurant’s colors and identity?', answer: 'Yes. Your page is made to feel like your restaurant, from the name and colors to the food photos and menu presentation.' },
  ],
} as const;